# Generated by Django 5.2.8 on 2025-11-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(verbose_name=100)),
                ('Description', models.CharField(verbose_name=1000)),
                ('Date_Created', models.DateTimeField(auto_now_add=True)),
                ('Is_Done', models.BooleanField()),
            ],
        ),
    ]
