# Generated by Django 5.2.8 on 2025-11-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Description',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='Title',
            field=models.CharField(max_length=100),
        ),
    ]
